#include <string>

struct myStruct
{
	std::string str;
	char * name_ptr;
	int int_val;
	char character;
};

enum
{
	ID_SYMBOL,
	CHARACTER_SYMBOL,
	EOF_SYMBOL,
	INTEGER_SYMBOL,
	STRING_SYMBOL,
	ARRAY_SYMBOL, 		
	BEGIN_SYMBOL, 		
	ELSE_SYMBOL,			
	ELSEIF_SYMBOL,		
	IF_SYMBOL,			
	OF_SYMBOL,			
	RECORD_SYMBOL,		
	REPEAT_SYMBOL,		
	TO_SYMBOL, 			
	TYPE_SYMBOL,			
	CHR_SYMBOL,			
	CONST_SYMBOL,		
	DO_SYMBOL,			
	END_SYMBOL,			
	FOR_SYMBOL,			
	FORWARD_SYMBOL, 		
	ORD_SYMBOL,			
	PRED_SYMBOL,			
	PROCEDURE_SYMBOL,	
	RETURN_SYMBOL,		
	STOP_SYMBOL,			
	SUCC_SYMBOL,			
	UNTIL_SYMBOL, 		
	VAR_SYMBOL,			
	WHILE_SYMBOL,		
	DOWNTO_SYMBOL,		
	FUNCTION_SYMBOL,		
	READ_SYMBOL,			
	THEN_SYMBOL,			
	WRITE_SYMBOL,
	ASSIGN_SYMBOL,
	ADD_SYMBOL,
	SUB_SYMBOL,
	MULT_SYMBOL,
	DIV_SYMBOL,
	AND_SYMBOL,
	OR_SYMBOL,
	NOT_SYMBOL,
	EQUAL_SYMBOL,
	NOT_EQUAL_SYMBOL,
	LESS_SYMBOL,
	LESS_EQUAL_SYMBOL,
	GREAT_SYMBOL,
	GREAT_EQUAL_SYMBOL,
	DOT_SYMBOL,
	COMMA_SYMBOL,
	COLON_SYMBOL,
	SEMI_COLON_SYMBOL,
	LEFT_BRACE_SYMBOL,
	RIGHT_BRACE_SYMBOL,
	LEFT_SQUARE_SYMBOL,
	RIGHT_SQUARE_SYMBOL,
	PERCENT_SYMBOL
};

